#!/usr/bin/env node
// Assembles client/{index.html,style.css,main.js} into src/client-html.ts, a
// generated module exporting the page as one self-contained string. The
// snapshot placeholder is deliberately left intact so makeSnapshotHtml can
// swap in embedded data at runtime.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SNAPSHOT_MARKER = '<!--__SNAPSHOT_DATA__-->';

const packageDir = join(import.meta.dirname, '..');
const clientDir = join(packageDir, 'client');
const outFile = join(packageDir, 'src', 'client-html.ts');

const html = readFileSync(join(clientDir, 'index.html'), 'utf8');
const css = readFileSync(join(clientDir, 'style.css'), 'utf8');
const script = readFileSync(join(clientDir, 'main.js'), 'utf8');

const page = html.replace('<!--__STYLE__-->', () => css.trim()).replace('<!--__SCRIPT__-->', () => script.trim());

for (const marker of ['<!--__STYLE__-->', '<!--__SCRIPT__-->']) {
  if (page.includes(marker)) throw new Error(`gen-client: placeholder ${marker} was not replaced`);
}
if (!page.includes(SNAPSHOT_MARKER)) {
  throw new Error(`gen-client: ${SNAPSHOT_MARKER} must survive into the template`);
}

writeFileSync(
  outFile,
  [
    '// GENERATED by scripts/gen-client.mjs from client/. Do not edit by hand.',
    '',
    `export const SNAPSHOT_MARKER = ${JSON.stringify(SNAPSHOT_MARKER)};`,
    '',
    `export const CLIENT_HTML = ${JSON.stringify(page)};`,
    '',
  ].join('\n'),
);

console.log(`gen-client: wrote src/client-html.ts (${page.length} bytes)`);
